### ISSUE TITLE
Problem with executing git submodule update --init --recursive and errors during task maze

### ISSUE THREAD

**Issue by timenotwait** [idiap/sigma-gpt#1]
Thank you for your excellent work on this project.

I encountered an issue while trying to execute the command git submodule update --init --recursive. As a workaround, I manually downloaded the corresponding version from the Picoclvr link provided in the repository.

However, despite following these steps, I still encounter errors when executing task maze. Here is the error message I receive:
![image](https://github.com/idiap/sigma-gpt/assets/109077044/b68b0dc5-e375-4f16-a7c5-e5272c13da33)

How could I fix it ? I would appreciate any guidance or suggestions on how to resolve this issue.

**Comment by ArnaudPannatier** [comment]
Hey ! Thanks for your interest in our work.

I've just checked again with a fresh install and it should work.

For the `git submodule update --init --recursive` did you try running that at the root of the repository (in the same folder than the `.gitmodules` ?

For the command, I know that François Fleuret updated his picoclvr repository with new stuff. It might have broken a few things. Maybe try to checkout to commit ` cf94b49` from inside the picoclvr repository. (it is the commit by default in the submodule.

```
git checkout cf94b49
```
to run in PicoCLVR repository

Then what command are you running ? 
A command that works on my side is 

```
python main.py --task maze --training_strategy="shuffle" --nb_train_samples 100 --nb_test_samples 100 
```
(I decreased the number of samples for faster debug)

**Comment by timenotwait** [comment]
I executed the command you mentioned, but at the end I still get the same error...

**Comment by ArnaudPannatier** [comment]
It could still be a problem of submodules or conda version. 
Did you create a new env?

What are the results of the following commands :

```
git submodule status
```
should be 
```
 cf94b49d085ec05e1053b49b7e796afa3f593a28 non-nlp/picoclvr (heads/master)
 9755682b981a45507f6eb9b11eadef8cb83cebd5 text/nanoGPT (heads/master)
```

or 
```
cd non-nlp/picoclvr
git log -1 
```
should show the same commit.

Or if it's an env problem what are the results of your 
`conda list` or `pip freeze` ?

**Comment by ArnaudPannatier** [comment]
because it seem to be an error related to the batch size dimension, which is weird. So I would be really interested of being able to replicate this error

**Comment by timenotwait** [comment]
Thank you for your enthusiastic response.
The result of the command looks fine:
![image](https://github.com/user-attachments/assets/d479da77-c06a-4e1c-a91b-4d66da07420f)
My CUDA driver version is 12.2.
By the way,the bug did not occur at the beginning, but after running for about 10 minutes.
I haven't made any changes to the code, the conda list is a bit long：


# packages in environment at /home/plan/miniconda3/envs/sigma-gpt-1:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_sysroot_linux-64_curr_repodata_hack 3                   haa98f57_10  
binutils                  2.38                 h1680402_1  
binutils_impl_linux-64    2.38                 h2a08ee3_1  
binutils_linux-64         2.38.0               hc2dff05_0  
black                     24.4.2          py310h06a4308_0  
blas                      1.0                         mkl  
bottleneck                1.3.7           py310ha9d4c09_0  
brotli                    1.0.9                h5eee18b_8  
brotli-bin                1.0.9                h5eee18b_8  
brotli-python             1.0.9           py310h6a678d5_8  
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2024.7.2             h06a4308_0  
cairo                     1.16.0               hb05425b_5  
cccl                      2.4.0                h7ab4013_0    conda-forge
certifi                   2024.7.4        py310h06a4308_0  
cffi                      1.16.0          py310h5eee18b_1  
cfgv                      3.4.0           py310h06a4308_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.7           py310h06a4308_0  
contourpy                 1.2.0           py310hdb19cb5_0  
cuda                      11.7.1                        0    nvidia
cuda-cccl                 12.5.39              ha770c72_0    conda-forge
cuda-cccl_linux-64        12.5.39              ha770c72_0    conda-forge
cuda-command-line-tools   11.7.1                        0    nvidia
cuda-compiler             12.4.1               h6a678d5_1  
cuda-cudart               11.7.99                       0    nvidia
cuda-cudart-dev           11.7.99                       0    nvidia
cuda-cuobjdump            12.4.127                      0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-cuxxfilt             12.4.127                      0    nvidia
cuda-demo-suite           12.4.127                      0    nvidia
cuda-documentation        12.4.127                      0    nvidia
cuda-driver-dev           12.5.82              he02047a_0    conda-forge
cuda-driver-dev_linux-64  12.5.82              h85509e4_0    conda-forge
cuda-gdb                  12.5.82                       0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-libraries-dev        12.5.1                        0    nvidia
cuda-memcheck             11.8.86                       0    nvidia
cuda-nsight               12.5.82              ha770c72_0    conda-forge
cuda-nvcc                 12.4.131                      0    nvidia
cuda-nvdisasm             12.5.39              he02047a_0    conda-forge
cuda-nvml-dev             12.5.82              he02047a_0    conda-forge
cuda-nvprof               12.5.82              he02047a_0    conda-forge
cuda-nvprune              12.4.127                      0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvrtc-dev            11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-nvvp                 12.5.82              he02047a_0    conda-forge
cuda-opencl               12.5.39              he02047a_0    conda-forge
cuda-opencl-dev           12.5.39              he02047a_0    conda-forge
cuda-profiler-api         12.5.39              ha770c72_0    conda-forge
cuda-runtime              11.7.1                        0    nvidia
cuda-sanitizer-api        12.5.81              he02047a_0    conda-forge
cuda-toolkit              11.7.1                        0    nvidia
cuda-tools                11.7.1                        0    nvidia
cuda-version              12.5                 hd4f0392_3    conda-forge
cuda-visual-tools         12.5.1               ha770c72_0    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0  
cyrus-sasl                2.1.28               h52b45da_1  
dbus                      1.13.18              hb2f20db_0  
distlib                   0.3.8           py310h06a4308_0  
einops                    0.8.0              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h6a678d5_0  
ffmpeg                    4.2.2                h20bf706_0  
filelock                  3.13.1          py310h06a4308_0  
fontconfig                2.14.1               h4c34cd2_2  
fonttools                 4.51.0          py310h5eee18b_0  
freetype                  2.12.1               h4a9f257_0  
gcc_impl_linux-64         11.2.0               h1234567_1  
gcc_linux-64              11.2.0               h5c386dc_0  
gds-tools                 1.10.1.7             he02047a_0    conda-forge
glib                      2.78.4               h6a678d5_0  
glib-tools                2.78.4               h6a678d5_0  
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2           py310heeb90bb_0  
gnutls                    3.6.15               he1e5248_0  
gst-plugins-base          1.14.1               h6a678d5_1  
gstreamer                 1.14.1               h5eee18b_1  
gxx_impl_linux-64         11.2.0               h1234567_1  
gxx_linux-64              11.2.0               hc2dff05_0  
icu                       73.1                 h6a678d5_0  
identify                  2.5.5           py310h06a4308_0  
idna                      3.7             py310h06a4308_0  
intel-openmp              2023.1.0         hdb19cb5_46306  
jinja2                    3.1.4           py310h06a4308_0  
jpeg                      9e                   h5eee18b_1  
kernel-headers_linux-64   3.10.0              h57e8cba_10  
kiwisolver                1.4.4           py310h6a678d5_0  
krb5                      1.20.1               h143b758_1  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libbrotlicommon           1.0.9                h5eee18b_8  
libbrotlidec              1.0.9                h5eee18b_8  
libbrotlienc              1.0.9                h5eee18b_8  
libclang                  14.0.6          default_hc6dbbc7_1  
libclang13                14.0.6          default_he11475f_1  
libcublas                 11.10.3.66                    0    nvidia
libcublas-dev             11.10.3.66                    0    nvidia
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufft-dev              10.7.2.124           h98a8f43_0    nvidia
libcufile                 1.10.1.7             he02047a_0    conda-forge
libcufile-dev             1.10.1.7             he02047a_0    conda-forge
libcups                   2.4.2                h2d74bed_1  
libcurand                 10.3.6.82            he02047a_0    conda-forge
libcurand-dev             10.3.6.82            he02047a_0    conda-forge
libcusolver               11.4.0.1                      0    nvidia
libcusolver-dev           11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libcusparse-dev           11.7.4.91                     0    nvidia
libdeflate                1.17                 h5eee18b_1  
libedit                   3.1.20230828         h5eee18b_0  
libffi                    3.4.4                h6a678d5_1  
libgcc-devel_linux-64     11.2.0               h1234567_1  
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libglib                   2.78.4               hdc74915_0  
libgomp                   14.1.0               h77fa898_0    conda-forge
libiconv                  1.16                 h5eee18b_3  
libidn2                   2.3.4                h5eee18b_0  
libllvm14                 14.0.6               hdb19cb5_3  
libnpp                    11.7.4.75                     0    nvidia
libnpp-dev                11.7.4.75                     0    nvidia
libnvfatbin               12.5.82              he02047a_0    conda-forge
libnvfatbin-dev           12.5.82              he02047a_0    conda-forge
libnvjitlink              12.5.82              he02047a_0    conda-forge
libnvjitlink-dev          12.5.82              he02047a_0    conda-forge
libnvjpeg                 11.8.0.2                      0    nvidia
libnvjpeg-dev             11.8.0.2                      0    nvidia
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.39               h5eee18b_0  
libpq                     12.17                hdbd6064_0  
libstdcxx-devel_linux-64  11.2.0               h1234567_1  
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.1                h6a678d5_0  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.41.5               h5eee18b_0  
libvpx                    1.7.0                h439df22_0  
libwebp-base              1.3.2                h5eee18b_0  
libxcb                    1.15                 h7f8727e_0  
libxkbcommon              1.0.1                h5eee18b_1  
libxml2                   2.10.4               hfdd30dd_2  
lz4-c                     1.9.4                h6a678d5_1  
markupsafe                2.1.3           py310h5eee18b_0  
matplotlib                3.8.4           py310h06a4308_0  
matplotlib-base           3.8.4           py310h1128e8f_0  
mkl                       2023.1.0         h213fc3f_46344  
mkl-service               2.4.0           py310h5eee18b_1  
mkl_fft                   1.3.8           py310h5eee18b_0  
mkl_random                1.2.4           py310hdb19cb5_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.3.0           py310h06a4308_0  
mypy_extensions           1.0.0           py310h06a4308_0  
mysql                     5.7.24               h721c034_2  
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  3.3             py310h06a4308_0  
nodeenv                   1.7.0           py310h06a4308_0  
nsight-compute            2024.2.1.2                    2    nvidia
nspr                      4.35                 h6a678d5_0  
nss                       3.89.1               h6a678d5_0  
numexpr                   2.8.7           py310h85018f9_0  
numpy                     1.26.4          py310h5f9d8c6_0  
numpy-base                1.26.4          py310hb5e798b_0  
ocl-icd                   2.3.2                h5eee18b_1  
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.4.0                h9ca470c_2  
openssl                   3.0.14               h5eee18b_0  
packaging                 24.1            py310h06a4308_0  
pandas                    2.2.2           py310h6a678d5_0  
pathspec                  0.10.3          py310h06a4308_0  
pcre2                     10.42                hebb0a14_1  
pillow                    10.3.0          py310h5eee18b_0  
pip                       24.0            py310h06a4308_0  
pixman                    0.40.0               h7f8727e_1  
platformdirs              3.10.0          py310h06a4308_0  
ply                       3.11            py310h06a4308_0  
pre-commit                3.4.0           py310h06a4308_1  
pycparser                 2.21               pyhd3eb1b0_0  
pyparsing                 3.0.9           py310h06a4308_0  
pyqt                      5.15.10         py310h6a678d5_0  
pyqt5-sip                 12.13.0         py310h5eee18b_0  
pysocks                   1.7.1           py310h06a4308_0  
python                    3.10.14              h955ad1f_1  
python-dateutil           2.9.0post0      py310h06a4308_2  
python-tzdata             2023.3             pyhd3eb1b0_0  
python_abi                3.10                    2_cp310    conda-forge
pytorch                   2.0.1           py3.10_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.1          py310h06a4308_0  
pyyaml                    6.0.1           py310h5eee18b_0  
qt-main                   5.15.2              h53bd1ea_10  
readline                  8.2                  h5eee18b_0  
regex                     2023.10.3       py310h5eee18b_0  
requests                  2.32.2          py310h06a4308_0  
setuptools                69.5.1          py310h06a4308_0  
sip                       6.7.12          py310h6a678d5_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.45.3               h5eee18b_0  
sympy                     1.12            py310h06a4308_0  
sysroot_linux-64          2.17                h57e8cba_10  
tbb                       2021.8.0             hdb19cb5_0  
tiktoken                  0.7.0           py310ha058ca7_0    conda-forge
tk                        8.6.14               h39e8969_0  
tomli                     2.0.1           py310h06a4308_0  
torchtriton               2.0.0                     py310    pytorch
torchvision               0.15.2              py310_cu117    pytorch
tornado                   6.4.1           py310h5eee18b_0  
tqdm                      4.66.4          py310h2f386ee_0  
typing_extensions         4.11.0          py310h06a4308_0  
tzdata                    2024a                h04d1e81_0  
ukkonen                   1.0.1           py310hdb19cb5_0  
unicodedata2              15.1.0          py310h5eee18b_0  
urllib3                   2.2.2           py310h06a4308_0  
virtualenv                20.26.1         py310h06a4308_0  
wheel                     0.43.0          py310h06a4308_0  
x264                      1!157.20191217       h7b6447c_0  
xz                        5.4.6                h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.13               h5eee18b_1  
zstd                      1.5.5                hc292b87_2

**Comment by timenotwait** [comment]
Thank you for your enthusiastic response.
The result of the command looks fine:
![image](https://github.com/user-attachments/assets/d479da77-c06a-4e1c-a91b-4d66da07420f)
My CUDA driver version is 12.2.
By the way,the bug did not occur at the beginning, but after running for about 10 minutes.
I haven't made any changes to the code, and the conda list is a bit long,here I list a part of it(I only used the yml file you provided to create it):

![image](https://github.com/user-attachments/assets/5551024e-0714-49a4-a82c-127d5d139d30)
![image](https://github.com/user-attachments/assets/457e7ea6-ee7d-48f7-9268-4e40143b5a8e)
![image](https://github.com/user-attachments/assets/febbe20d-05ab-40ae-a8a5-cd98a1b0ab07)
![image](https://github.com/user-attachments/assets/7cd0cb00-5dfc-4640-85e6-36b0c128fd5a)

**Comment by ArnaudPannatier** [comment]
Thanks a lot for your extensive answer, it turns out that you were right, there was a bug late in the pipeline that I introduced during refactoring. Sorry for that. I've corrected it and am running the whole pipeline again this night, + coming day(s) to be sure that everything is in order. I'll let you know once it's done.

**Comment by ArnaudPannatier** [comment]
It seems to work correctly with the fix. Let me know if it now works on your side. Thanks a lot for spotting that mistake

**Comment by timenotwait** [comment]
The program ran smoothly this time 😄. Thanks again for your helpful response!

**Comment by ArnaudPannatier** [comment]
Thanks for noticing the bug and following up through !
